init: add the Eclipse OSD implementation of the Open System Descripti…
krono-safe/eosd pull request #1
Opened 2019-03-29 16:03 UTC by klopes25

Eclipse OSD is the implementation of the Open System Description format with the Eclipse Modeling Framework.

2019-03-29 16:17 UTC, fthomasfr approved these changes

2019-03-29 17:00 UTC, jeanguyomarch requested changes
To sum-up the key points of our discussion:
- the documentation generated from the javadoc should not be committed in this repository. Once travis is setup, it could automatically build the doc for us.
- We should make sure that files end with a newline (otherwise, git usually complains about these files).
- "Huge" binary files (such as videos or large images) should be stored using [Git LFS](https://git-lfs.github.com/). [This tutorial](https://help.github.com/en/articles/configuring-git-large-file-storage) should provide hints to do so.
- A [code of conduct](https://github.com/krono-safe/vim-asterios/blob/master/CODE_OF_CONDUCT.md) would be nice to add.
- Jenkinsfiles should not be committed here, as they are inherent to an internal Jenkins system. Ultimately, they will be replaced with something like `.travis.yml`.

2019-03-29 17:00 UTC, jeanguyomarch commented on .mvn/extensions.xml
> +</extensions>
Is it normal not to have a newline at the end of the file?

2019-03-29 17:00 UTC, jeanguyomarch commented on documentation/SampleProject/model/sampleProject.ecore
> +<?xml version="1.0" encoding="UTF-8"?>
Isn't it a generated file? Generated files should not be committed to the repository.

2019-03-29 17:06 UTC, jeanguyomarch commented
Also, the commit message is not properly written. This causes github to truncate the message, which is quite disgracious. You may want to follow [this article](https://thoughtbot.com/blog/5-useful-tips-for-a-better-commit-message).

2019-04-24 12:36 UTC, klopes25 commented on documentation/SampleProject/model/sampleProject.ecore
> +<?xml version="1.0" encoding="UTF-8"?>
The generated files are no longer in the repository.

2019-04-24 12:43 UTC, klopes25 commented on .mvn/extensions.xml
> +</extensions>
No, it's changed.

2019-05-09 12:52 UTC, jeanguyomarch commented
I am not competent to judge the Java part. The rest looks good to me. Any additional thoughs @superwhoopy?

2019-05-09 12:52 UTC, jeanguyomarch approved these changes

2019-05-14 08:31 UTC, superwhoopy approved these changes
Champagne ! 🍾 
:-)

2019-05-14 08:31 UTC, merged